### ISSUE TITLE
Some Confusion on Unembedding

### ISSUE THREAD

**Issue by afspies** [neelnanda-io/TransformerLens#179]
Hey,

If one unembeds from intermediate layers of the residual stream, the lack of normalization (coming from `layer_norm_pre`) leads to different (intuitively, less likely to be sensible) results. 

I don't know if there is a warning about this / whether we might want to add a `include_normalization` flag to `model.unembed(...)`

Thanks!

Alex

**Comment by neelnanda-io** [comment]
Er, so I agree this is a thing people might be confused about, but it seems
basically impossible to solve. In particular, `ln_final` does not live in
the unembedding, it lives in the HookedTransformer class (and I do not want
to change this for backwards compatability reasons). Though it's not
obvious to me which is more principled - if a feature *is *intended to
directly affect the output, it will only be affected by the *final *layernorm
scaling factor, and applying layernorm with a different scale factor
(because later layers are removed) is sketchy. (This can actually get you
pretty misleading results, since the final few layers increase the norm a
*lot*!)

I also just want people to directly multiply by W_U lol, the unembed isn't
intended to be directly applied in isolation!

I'd be down to have a comment in the unembed class warning about this?
