### ISSUE TITLE
[Proposal] Improve porting models from hugging face

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/TransformerLens#205]
### Proposal 

Improve the way we handle the `config.json` objects from saved models on HF.

### Motivation

It was a pain porting the Redwood model as there were a bunch of extra config options I needed to add

E.g that model is an attention only model and yet https://github.com/neelnanda-io/TransformerLens/blob/649d3be19b0f7283fd81d06e4f94aef8cb6b2cfe/transformer_lens/loading_from_pretrained.py#L450 requires d_mlp to be supplied

### Pitch

Make it easy to load `config.json` files for HookedTransformers from huggingface. Make it backwards compatible with all the models like https://huggingface.co/NeelNanda/SoLU_1L128W_C4_Width_Scan/blob/main/config.json but much easier to use, perhaps with a tutorial

**Comment by neelnanda-io** [comment]
Having a tutorial for loading in a model would be great!

One major problem is that HuggingFace configs are not consistently formatted. If they are, we could just have a "convertHFtoTLconfig" function that people can use. This is part of why I force TransformerLens to have a consistent model and config class, and go through the tedious steps of conversion.

Case in point, compare the GPT-2 config and the Pythia config
https://huggingface.co/gpt2/blob/main/config.json
https://huggingface.co/EleutherAI/pythia-1.4b-deduped/blob/main/config.json

GPT-2 doesn't even have d_mlp since it's hard-coded as 4*d_model, Pythia calls it intermediate_size. And GPT-2 has n_positions while Pythia has max_position_embeddings.

It's a headache...
