### ISSUE TITLE
[Proposal] Find a way to run all the tutorials and check that they don't generate errors

### ISSUE THREAD

**Issue by jbloomAus** [neelnanda-io/TransformerLens#213]
### Proposal 

Find a way to run all the tutorials and check that they don't generate errors.

### Motivation

This is a good way to avoid breaking compatibility with the tutorials which also stand in as an acceptance test. 

### Alternatives

We write more tests and be careful when we edit tutorials. 

### Additional context

We probably have had some silent errors where notebooks stop working and I'd like to avoid this in the future. 

### Checklist

- [x ] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by bryce13950** [comment]
Is the file `demos/Othello_GPT.ipynb` still even relevant? It seems that all but this tutorial are in the project root, and the file itself has an issue with torchtyping not being found.

**Comment by neelnanda-io** [comment]
That file is still relevant, though would be good to fix the error. I made
the demos folder because having all demos in root seemed unsustainable, and
intend future ones to go in that folder, but didn't want to move the old
ones to avoid breaking links. Possibly this is the worst of both worlds, idk

**Comment by bryce13950** [comment]
I was actually going to suggest that we move all tutorials into their own directory for testing purposes. It seems to me that the most important thing for these tutorials is that they can execute without omitting errors. I don't know if there is any reason to inspect output of actual function calls, since the other test suites should be doing that before we get to this suite anyways. With that in mind, we can scan a the directory `docs` for all `ipynb` files and then have those all automatically run through a test that simply checks for errors omitted. That would save any hassle of maintaining this. Whenever anyone creates a new tutorial, as long someone puts those files into `docs`, they will automatically be tested without the need to manually configure the test. If I am wrong on my assumption that we do not need to inspect specific function returns then let me know.

With all of that in mind, I will go ahead and move all tutorials to `docs`, search the source base for any references to those files and update them according. As for the concern with redirects, I am more than happy to setup wildcard redirects for those. I know there may be a few places where it needs to be setup, but I will start off by experimenting a bit to answer a few questions that I have.

**Comment by jbloomAus** [comment]
Some notes:
- Moving all tutorials into their own directory is probably worth it. I'm curious about what downstream issues might create. @neelnanda-io, can we solve these?
- The directory shouldn't be called docs as that's a sphinx directory. Maybe call it tutorials or something. 
- Don't forget when you set up the github action to make sure it triggers on PR's so we get to see this working in the PR you make. 
Thanks Bryce!

**Comment by bryce13950** [comment]
Well I was also thinking to rearrange that even before I setup the tests. It seems like people are contributing to those files at least relatively regularly, so getting that rearranged for everyone, and then getting the tests in is probably the way to go. I want to make sure the tests are actually passing when I submit them into the repo, and I don't know how much debugging there is going to be to get all tutorials up to speed. Expect two pull requests, one for the rearrangement relatively quickly, and the second that resolves this issue once I have the full suite running and passing.

**Comment by bryce13950** [comment]
Could someone give me access to the repo as a collaborator? I found a potential way to redirect the notebooks in GitHub pages, but I cannot really move forward with figuring out how to implement this without being able to poke around with the actions on the repo, so that I can recreate those actions on my fork exactly as is in order to test the changes to the pages site.

**Comment by neelnanda-io** [comment]
I favour calling the folder demos. Bryce convinced me it's worth the
headache of moving them. I agree that just checking that they run from the
top is sufficient, you do not need to check function out. One option is to
have each demo own its own branch of the repo and install the library from
that branch -they can become a bit out of date, but they will never break
on a new PR to main I think. I'll try to add you as a collaborator this
afternoon, please ping on slack if I forget

**Comment by bryce13950** [comment]
Hey all. I wanted to touch on this a bit yesterday, but ended up having a crazy day with another project. I have been messaging both of you about this separately, and I have especially been messaging @jbloomAus while figuring out parts of this, so thought it would be a good idea to bring it all up to speed so that we are all on the same page.

I spent quite a bit of time looking into figuring out how to redirect from `/Main_Demo.ipynb` to `/tutorials/Main_demo.ipynb` on both GitHub and colab, which led me into a bit of a rabbit hole involving git hub actions. Unfortunately, the conclusion that I came to after checking a number of possible plugins and stack overflow discussions is that it is simply not possible to integrate something like that into GitHub. I have not made any conclusions about colab, but the solution I have found basically solves the issue in both systems. The solution that I have found as being the accepted way to go is to simply make a placeholder for a couple months with the same name that informs people that the real file has been moved. Not the most elegant solution, but it does solve the issue with breaking links out in the wild, and it is only something that needs to be there for a period of time.

As for the directory name, I would put my vote in with @neelnanda-io on this one. I understand the issue with not wanting it to have the same name as the directory in the GitHub pages site. However, given that there isn't an elegant solution to redirects, leaving them as demos makes it so that there is one less file we need to worry about.

For the placeholders, I think we are probably fine with just putting a placeholder up for `Main_demo.ipynb`. If someone somehow hits a link to one of the other files, then realistically they are probably going to go to the project root, see the other `ipynb` file, open that one, and from there understand where they can find the one they are looking for. It may not be a catch all for all cases, but I am assuming that most public links to these files are going to the main demo.

On the subject of public links, the most important one is on Neel's square space, which makes coordinating that really easy. I am going to do a little research on what sites are linking to these demos, and put together a little report on that. There is a pretty good chance that the people linking to these files are also people in the slack, which could make getting public links updated relatively easy.

**Comment by bryce13950** [comment]
We may be in the clear. It looks like most people are linking to Neel's site. https://ahrefs.com/backlink-checker

<img width="890" alt="image" src="https://user-images.githubusercontent.com/6487928/229314276-ef751c35-95c4-4f9e-8109-014d9d498ef0.png">

This isn't for certain, but it's going to be mostly accurate.

**Comment by jbloomAus** [comment]
@neelnanda-io, responding to this first but will respond to other discussion points.

"One option is to have each demo own its branch of the repo and install the library from that branch -they can become a bit out of date, but they will never break on a new PR to main, I think." - **I would strongly advise against this because it's a form of code duplication which will create headaches**. For example, imagine a tutorial has a mistake. To fix it, you need to update the code. We then need to decide whether to bring the whole tutorial in line with the latest code so we can push a fix or branch the code at that moment and install a fix only for that tutorial which may/may not need duplication on the main branch. 

Moreover, I think it's important the code in tutorials to reflect the current package. Having tutorials break on PRs can be avoided by running tutorials as a form of regression test. I don't see this so much as creating work as revealing work that needs to be done anyway, since it would be good to know if changes are being made that break existing analysis code since that will correlate with causing problems for users. 

With respect to other issues:
- redirects sound hard, but I'd like not to cause trouble for Neel's links. We should work with Neel to solve this, but I think putting the redirects in the code base may not be the best way. Can we update Squarespace? 
- not fussed what we call the folder long as people can find it. "Demos" works and causes no conflicts.

**Comment by neelnanda-io** [comment]
Updating Squarespace is trivial, to be clear. The issue is people not using
my redirect links (I made the links to help solve this kind of problem, so
go past Neel!)

Fair point re code duplication, though I do think that most fixes for a
tutorial will be to the notebook not to the underlying codebase. I do think
that if we take regression tests seriously and avoid any breaking code that
that would be sufficient for this concern

**Comment by bryce13950** [comment]
To be clear, the image I posted last is from a tool that shows you pages that are linking to a url. It is not 100% accurate, but its database does not have any instances of the main demo on GitHub. In contrast, Neels redirect has 7 entries in this tools database.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/6487928/229626562-f5fbd6f2-e53d-4634-b450-fc087dcc6324.png">

The concern about redirects may not be a big deal at all.

**Comment by neelnanda-io** [comment]
Ah, great, sounds like not much of an issue then. What tool is this?

**Comment by bryce13950** [comment]
The website is https://ahrefs.com. The tool specifically is the backlink checker. There are a number of tools on that site that can be used, so its a relatively useful site.

**Comment by bryce13950** [comment]
Hey all, I am starting to work through getting the test to pass, and I have come up to something, which I am not sure how to get by. Basically, I have found that some of these docs require that an Nvidia driver to be installed on the running machine. In Github, has anyone messed around with figuring out if there is a way to run actions on a machine connected to an Nvidia GPU?

**Comment by bryce13950** [comment]
In most of these demos, the top have a check for if the file is running in colab. If it is, it then installs the dependencies for the demo. If not, then the demo always fails due to those dependencies not being preset. Is there a reason why it is only installing dependencies in colab?

**Comment by alan-cooney** [comment]
Closing as stale, and I think we'll end up moving a lot of the notebook stuff to docstring documentation anyway
