### ISSUE TITLE
[Proposal] Make tokenization default match models

### ISSUE THREAD

**Issue by UlisseMini** [neelnanda-io/TransformerLens#282]
### Proposal 

Make the default `prepend_bos` in `to_tokens` the same as what the model was trained with. Currently, the default tokenization for `GPT-2` includes a BOS token.

### Motivation

In [Steering GPT-2-XL by adding an activation vector](https://www.lesswrong.com/posts/5spBue2z2tw4JuDCx/steering-gpt-2-xl-by-adding-an-activation-vector) we unintentionally used `prepend_bos=True` on GPT2, despite GPT2 being trained without BOS tokens.

### Pitch

It would be good to prevent future people from shooting themselves in the foot, with a tokenization that doesn't match the model.

### Alternatives

Adding informative warnings could be better than a complicated defaults system.

**Comment by neelnanda-io** [comment]
This was intentional, even though Gpt2 wasn't trained with a BOS token it
works basically fine (and I believe it was trained on concatenated
documents separated by a BOS token so it's not ridiculous). The reason is
that models treat the first token WEIRDLY and not having a BOS token means
people shoot themselves in the foot.

Sorry you feel that it messed up your project though! (though in my opinion
this is a completely fine and reasonable thing to do in your project).
Warnings are maybe reasonable, though I would favour them in a docstring or
FAQ, I wouldn't want these warnings printed every time someone uses gpt2!

**Comment by UlisseMini** [comment]
Ah I see, that makes sense thanks!
